class Attribute:

    NAME = 'Mouse'

    MINIMUM_HOVERING_TIME = 1


class State:

    FREE = 'FREE'
    NOT_BUZY = 'NOT_BUZY'

    LEFT_CLICK_UP = 'LEFT_CLICK_UP'
    LEFT_CLICK_DOWN = 'LEFT_CLICK_DOWN'
    END_OF_LIFE_CYCLE = 'END_OF_LIFE_CYCLE'
    INVALID_STATE = 'INVALID_STATE'
