dbREGISTRATION = '__registration__'
dbPASSWORD = '__password__'
dbCOURSES = '__courses__'
dbNOTHING = '__nothing__'
dbPAGE_DATA_SEPARATOR = '__#__'
dbCOMA = '__,__'
dbCOLON = '__:__'


dbPAGE = '__page__'
dbIMAGE = '__image__'
dbAUDIO = '__audio__'
dbFOWARD_BUTTON = '__FowardButton__'
dbBACKWARD_BUTTON = '__BackwardButton__'
dbPAGE_SCRIPT = '__pageScript__'
dbOPEN_SQUARE_BRACKETS = '__[__'
dbCLOSE_SQUARE_BRACKETS = '__]__'
